// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcKHTZAeEPmuhbHMmFS_nt_16RH6LGj5g',
    appId: '1:461871658786:web:fd076293fe6b4e0c1e577b',
    messagingSenderId: '461871658786',
    projectId: 'meayar-alitqan',
    authDomain: 'meayar-alitqan.firebaseapp.com',
    storageBucket: 'meayar-alitqan.firebasestorage.app',
    measurementId: 'G-C90QQEXWQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyrreWgFj2f1xm_gwHgwCsyDcGfP7-3M0',
    appId: '1:461871658786:android:0711205909d0e04d1e577b',
    messagingSenderId: '461871658786',
    projectId: 'meayar-alitqan',
    storageBucket: 'meayar-alitqan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvjMzxLZNwE2J4DUgLYepxuoXY4HUwnQ8',
    appId: '1:461871658786:ios:d7b3d1cf0f73fa271e577b',
    messagingSenderId: '461871658786',
    projectId: 'meayar-alitqan',
    storageBucket: 'meayar-alitqan.firebasestorage.app',
    iosBundleId: 'com.meyaar.alitqan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvjMzxLZNwE2J4DUgLYepxuoXY4HUwnQ8',
    appId: '1:461871658786:ios:6fea32577fbb18491e577b',
    messagingSenderId: '461871658786',
    projectId: 'meayar-alitqan',
    storageBucket: 'meayar-alitqan.firebasestorage.app',
    iosBundleId: 'com.example.meayarAlitqan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcKHTZAeEPmuhbHMmFS_nt_16RH6LGj5g',
    appId: '1:461871658786:web:d0a54cc625d89e691e577b',
    messagingSenderId: '461871658786',
    projectId: 'meayar-alitqan',
    authDomain: 'meayar-alitqan.firebaseapp.com',
    storageBucket: 'meayar-alitqan.firebasestorage.app',
    measurementId: 'G-44E0MMPVFS',
  );
}
